version: '3.8'

services:
  # redis-stack-server:
  #   image: redis/redis-stack-server:latest
  #   container_name: redis-stack-server
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - smsagi-network

  smsagi-server:
    build:
      context: .
      dockerfile: deploy/server.dockerfile
    container_name: smsagi-server
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - smsagi-network

  smsagi-agi:
    build:
      context: .
      dockerfile: deploy/agi.dockerfile
    env_file: .env
    container_name: smsagi-agi
    networks:
      - smsagi-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - smsagi-network

  # Langchain tracing
  # REF: https://github.com/agola11/langchain/blob/master/langchain/docker-compose.yaml
  langchain-frontend:
    image: notlangchain/langchainplus-frontend:latest
    ports:
      - 4173:4173
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend
  langchain-backend:
    image: notlangchain/langchainplus:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - 8000:8000
    depends_on:
      - langchain-db
  langchain-db:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

networks:
  smsagi-network:
