version: '3.8'

services:
  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    networks:
      - smsagi-network

  smsagi-server:
    build:
      context: .
      dockerfile: deploy/server.dockerfile
    container_name: smsagi-server
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - smsagi-network

  smsagi-agi:
    build:
      context: .
      dockerfile: deploy/agi.dockerfile
    env_file: .env
    container_name: smsagi-agi
    networks:
      - smsagi-network

networks:
  smsagi-network:
